exports.keywords = [
  "Circular Economy",
  "Linear Economy",
  "Resource Efficiency",
  "Waste Reduction",
  "Recycling",
  "Reuse",
  "Repair",
  "Remanufacturing",
  "Refurbishing",
  "Zero Waste",
  "Sustainable Production",
  "Sustainable Consumption",
  "Regenerative Resources",
  "Renewable Energy",
  "Life Cycle Assessment",
  "Cradle-to-Cradle",
  "Biomimicry",
  "Industrial Symbiosis",
  "Closed-Loop Systems",
  "Extended Producer Responsibility (EPR)",
  "Sharing Economy",
  "Product-Service Systems",
  "Eco-Design",
  "Green Procurement",
  "Material Flow Analysis",
  "Circular Business Models",
  "Circularity Indicators",
  "Circularity Gap",
  "Circular Supply Chains",
  "Circular Cities",
  "Circular Buildings",
  "Circular Textiles",
  "Circular Agriculture",
  "Circular Food Systems",
  "Circular Plastics",
  "Circular Electronics",
  "Circular Mobility",
  "Circular Water Management",
  "Circular Chemicals",
  "Circular Mining",
  "Circular Economy Strategies",
  "Circular Economy Policies",
  "Circular Economy Roadmaps",
  "Circular Economy Transition",
  "Just Transition",
  "Green Jobs",
  "Green Skills",
  "Green Innovation",
  "Green Entrepreneurship",
  "Green Recovery",
  "Climate Change Mitigation",
  "Climate Change Adaptation",
  "Biodiversity Conservation",
  "Sustainable Development Goals (SDGs)",
  "Nationally Determined Contributions (NDCs)",
];
