exports.csp_links = [
    "'self'",
    '*.sdg-innovation-commons.org',
    'sdg-innovation-commons.org',
    'https://unpkg.com',
    'https://fonts.googleapis.com',
    'https://fonts.gstatic.com',
    'https://www.google.com',
    'https://maxcdn.bootstrapcdn.com',
    'https://acclabplatforms.blob.core.windows.net',
    'https://cdn.jsdelivr.net',
    'https://code.jquery.com',
    'https://cdnjs.cloudflare.com',
    'https://design.undp.org',
  ];