# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - web-extract

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_18ad219195eb4c8e8ff1ca19ac826a96 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a414694aa2b649b0b8fec65b54692c9e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_18ad219195eb4c8e8ff1ca19ac826a96 }}/my-blog-scrapper:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'web-extract'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6e6b41204b95416896733c20c7ee7cc9 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_18ad219195eb4c8e8ff1ca19ac826a96 }}/my-blog-scrapper:${{ github.sha }}'